name: PR Build
on:
  pull_request:
concurrency:
  group: pr-build-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  pr-build:
    name: PR Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cds-core: ['', '@cds/core@^5.6.0']
        angular: ['Angular v13', 'Angular v14', 'Angular v15']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Update to Angular v14
        if: ${{matrix.angular == 'Angular v14' || matrix.angular == 'Angular v15'}}
        run: |
          npm run ng update @angular/core@14 @angular/cli@14
          git checkout -- projects/*
          npm run _lint:format:fix
      - name: Update to Angular v15
        if: ${{matrix.angular == 'Angular v15'}}
        run: |
          npm run ng update @angular/core@15 @angular/cli@15 -- --allow-dirty
          npm run _lint:format:fix
      - name: Install Alternate @cds/core Version
        if: ${{matrix.cds-core != ''}}
        run: npm install ${{matrix.cds-core}}
      - name: Disable Docs Build
        if: ${{matrix.cds-core != '' || matrix.angular != 'Angular v13'}}
        run: node ./scripts/clear-npm-script.js _build:demo _build:storybook
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Public Api Check
        if: ${{matrix.angular == 'Angular v13'}}
        run: npm run public-api:check
      - name: Upload Docs Artifact
        if: ${{matrix.cds-core == '' && matrix.angular == 'Angular v13'}}
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: dist/docs/
